<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-VHI7RBC" failures="2" tests="8" name="MyTestCase" time="6.023" errors="0" timestamp="30 Aug. 2023 02:20:27 GMT">
  <testcase classname="com.github.CreateANewRepo_POST_Request" name="CheckResponseTime" time="0.023"/>
  <testcase classname="com.github.CreateANewRepo_POST_Request" name="CheckStatus" time="0.002"/>
  <testcase classname="com.github.CreateANewRepo_POST_Request" name="PrintResponseBody" time="0.02"/>
  <testcase classname="com.github.CreateANewRepo_POST_Request" name="TestHeader" time="0.006"/>
  <testcase classname="com.github.DeleteRepo_DEL_Request" name="CheckContent" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [null] but found [application/json; charset=utf-8]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [application/json; charset=utf-8]
at com.github.DeleteRepo_DEL_Request.CheckContent(DeleteRepo_DEL_Request.java:72)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- CheckContent -->
  <testcase classname="com.github.DeleteRepo_DEL_Request" name="CheckResponseBody" time="0.001"/>
  <testcase classname="com.github.DeleteRepo_DEL_Request" name="CheckResponseTime" time="0.001"/>
  <testcase classname="com.github.DeleteRepo_DEL_Request" name="CheckStatus" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [204] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [204] but found [401]
at com.github.DeleteRepo_DEL_Request.CheckStatus(DeleteRepo_DEL_Request.java:54)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- CheckStatus -->
</testsuite> <!-- MyTestCase -->
